// Mocks generated by Mockito 5.4.4 from annotations
// in netflix_home/test/features/view_model/movies_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:netflix_home/core/api/data_state.dart' as _i2;
import 'package:netflix_home/features/movies/model/model.dart' as _i5;
import 'package:netflix_home/features/movies/repository/movies_rep.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepoImpl extends _i1.Mock implements _i3.MovieRepoImpl {
  MockMovieRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataState<List<_i5.MovieModel>>> getMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [],
        ),
        returnValue: _i4.Future<_i2.DataState<List<_i5.MovieModel>>>.value(
            _FakeDataState_0<List<_i5.MovieModel>>(
          this,
          Invocation.method(
            #getMovies,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataState<List<_i5.MovieModel>>>);
}
